name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install pylint pylint-json2html

    - name: Run Pylint and check score
      run: |
        pylint --output-format=json $(git ls-files '*.py') > pylint_output.json || true
        
        # Extract the score from the pylint_output.json
        pylint_score=$(jq '[.[] | .score] | add / length' pylint_output.json)
        echo "Pylint score: $pylint_score"

        # If the score is greater than or equal to 8, exit with code 0, otherwise exit with 1
        if (( $(echo "$pylint_score >= 8" | bc -l) )); then
          echo "Pylint score is above 8, passing the build."
          exit 0
        else
          echo "Pylint score is below 8, failing the build."
          exit 1
        fi
