name: Lint Code with Pylint

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:  # Run on pull requests to ensure code quality
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Set up the Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies and Pylint
      - name: Install dependencies and Pylint
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pylint

      # Step 4: Run Pylint
      - name: Run Pylint on Python files
        run: |
          source venv/bin/activate
          pylint $(git ls-files '*.py')
